### PR TITLE
Overview connect

### PR DESCRIPTION
**Pull request by alok620**
Added Overview functionality already merged main into it to make integration less painfull

### CODE REVIEW

**Comment by rdostale** [comment]
Looks good to me

**Review by gio-delaluz — APPROVED** [review]
Great job connecting the frontend to the backend and I can contribute to improving the design. But this is great and has my approval.

**Comment by BLopez04** [comment]
Good job all around

**Review by BLopez04 — APPROVED** [review]

**Comment by ryanvuu** [comment]
Great work, everything looks clean.

**Comment by NotMichaelHuang** [comment]
good stuff!

**Pull request merged**
