### PR TITLE
Test PR-9

### PR DESCRIPTION
**Pull request by gio-delaluz**
Design Changes
- Adding Edit Budget Button to Budget Overview Card

updateBudget()
- resolved some edge cases (i.e. inputting a word would result in NaN)

### CODE REVIEW

**Comment by BLopez04** [comment]
Looks good. Ill get it in ASAP.

**Comment by rdostale** [comment]
Looks good to me

**Comment by ryanvuu** [comment]
Everything seems good to me. Good work.

**Comment by NotMichaelHuang** [comment]
nice!

**Pull request merged**
