### PR TITLE
Move log out button to overview, add delete user

### PR DESCRIPTION
**Pull request by BLopez04**
I also:
- Removed the userid display from the table page
- Set the error message on login since it would always be an unauthorized token error sent from backend otherwise
- Deleted a bit of commented out code/fixed the endpoint for deleting a user

### CODE REVIEW

**Comment by rdostale** [comment]
Looks good to me

**Comment by alok620** [comment]
Great finishing touches really help the overall flow of the app

**Comment by ryanvuu** [comment]
Code looks good to me.

**Comment by NotMichaelHuang** [comment]
pretty good

**Pull request merged**
