### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by NotMichaelHuang**
Use Jest to test one non-trivial React component. The component should have some internal state (useState) and at least 3 inputs or buttons. Submit a test coverage report showing 80% coverage to get full credit.

### CODE REVIEW

**Comment by BLopez04** [comment]
Looks good

**Comment by rdostale** [comment]
Looks good to me

**Comment by alok620** [comment]
Great work! Looks good

**Comment by NotMichaelHuang** [comment]
Looks good on my end

**Comment by ryanvuu** [comment]
Looks great. Thanks for getting this done!

**Comment by gio-delaluz** [comment]
great work adding test coverage throughout the application

**Pull request merged**
