### PR TITLE
Frontend changes

### PR DESCRIPTION
**Pull request by ryanvuu**
Modified frontend to include a navbar. Added home buttons to return from login and signup pages. Added features section to the front page.

### CODE REVIEW

**Review by NotMichaelHuang — APPROVED** [review]

**Comment by rdostale** [comment]
The image on the Login page ends up covering the Navbar when the browser is full screened, disabling interactions.

**Review by rdostale — CHANGES_REQUESTED** [review]
Image covers navbar on Login page

**Review by alok620 — APPROVED** [review]

**Review by ryanvuu — COMMENTED** [review]
most recent push resolves @rdostale issue

**Comment by NotMichaelHuang** [comment]
wow, pretty good.

**Pull request merged**
